package ejemplo03.dominio;
// Generated 19-feb-2019 10:25:30 by Hibernate Tools 4.3.1



/**
 * Licencia generated by hbm2java
 */
public class Licencia  implements java.io.Serializable {


     private int expediente;
     private Local local;
     private int idLicencia;
     private String titulo;
     private String fechaCreacion;
     private String anyo;

    public Licencia() {
    }

    public Licencia(int expediente, Local local, int idLicencia, String titulo, String fechaCreacion, String anyo) {
       this.expediente = expediente;
       this.local = local;
       this.idLicencia = idLicencia;
       this.titulo = titulo;
       this.fechaCreacion = fechaCreacion;
       this.anyo = anyo;
    }

    public int getExpediente() {
        return this.expediente;
    }

    public void setExpediente(int expediente) {
        this.expediente = expediente;
    }
    public Local getLocal() {
        return this.local;
    }

    public void setLocal(Local local) {
        this.local = local;
    }
    public int getIdLicencia() {
        return this.idLicencia;
    }

    public void setIdLicencia(int idLicencia) {
        this.idLicencia = idLicencia;
    }
    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(String fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getAnyo() {
        return this.anyo;
    }

    public void setAnyo(String anyo) {
        this.anyo = anyo;
    }




}
