package ejemplo03.dominio;
// Generated 19-feb-2019 10:25:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Local generated by hbm2java
 */
public class Local  implements java.io.Serializable {


     private int id;
     private String emplazamiento;
     private String codigoPortal;
     private String codigoVia;
     private String numeroVia;
     private String refCatas;
     private String refMuni;
     private int poligono;
     private String zonaSaturada;
     private String comentarios;
     private Set licencias = new HashSet(0);

    public Local() {
    }

	
    public Local(int id, String emplazamiento, String codigoPortal, String codigoVia, String numeroVia, String refCatas, String refMuni, int poligono, String zonaSaturada, String comentarios) {
        this.id = id;
        this.emplazamiento = emplazamiento;
        this.codigoPortal = codigoPortal;
        this.codigoVia = codigoVia;
        this.numeroVia = numeroVia;
        this.refCatas = refCatas;
        this.refMuni = refMuni;
        this.poligono = poligono;
        this.zonaSaturada = zonaSaturada;
        this.comentarios = comentarios;
    }
    public Local(int id, String emplazamiento, String codigoPortal, String codigoVia, String numeroVia, String refCatas, String refMuni, int poligono, String zonaSaturada, String comentarios, Set licencias) {
       this.id = id;
       this.emplazamiento = emplazamiento;
       this.codigoPortal = codigoPortal;
       this.codigoVia = codigoVia;
       this.numeroVia = numeroVia;
       this.refCatas = refCatas;
       this.refMuni = refMuni;
       this.poligono = poligono;
       this.zonaSaturada = zonaSaturada;
       this.comentarios = comentarios;
       this.licencias = licencias;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getEmplazamiento() {
        return this.emplazamiento;
    }
    
    public void setEmplazamiento(String emplazamiento) {
        this.emplazamiento = emplazamiento;
    }
    public String getCodigoPortal() {
        return this.codigoPortal;
    }
    
    public void setCodigoPortal(String codigoPortal) {
        this.codigoPortal = codigoPortal;
    }
    public String getCodigoVia() {
        return this.codigoVia;
    }
    
    public void setCodigoVia(String codigoVia) {
        this.codigoVia = codigoVia;
    }
    public String getNumeroVia() {
        return this.numeroVia;
    }
    
    public void setNumeroVia(String numeroVia) {
        this.numeroVia = numeroVia;
    }
    public String getRefCatas() {
        return this.refCatas;
    }
    
    public void setRefCatas(String refCatas) {
        this.refCatas = refCatas;
    }
    public String getRefMuni() {
        return this.refMuni;
    }
    
    public void setRefMuni(String refMuni) {
        this.refMuni = refMuni;
    }
    public int getPoligono() {
        return this.poligono;
    }
    
    public void setPoligono(int poligono) {
        this.poligono = poligono;
    }
    public String getZonaSaturada() {
        return this.zonaSaturada;
    }
    
    public void setZonaSaturada(String zonaSaturada) {
        this.zonaSaturada = zonaSaturada;
    }
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }
    public Set getLicencias() {
        return this.licencias;
    }
    
    public void setLicencias(Set licencias) {
        this.licencias = licencias;
    }




}


